before_install:
  wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
before_script:
  - wget https://github.com/n1k0/casperjs/tarball/master -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.0.2/bin/
language: java
script:
  - java -version
  - javac -version
  - python -V
  - phantomjs -v
  - casperjs 
  - echo Hello from DUT INFO Blagnac
  - ls -alF
  - cd sprint_5
  - javac -cp .:./bin -d ./bin ./src/HelloMonde.java
  - javac -cp .:./bin:../junit.jar -d ./bin ./src/HelloMondeTest.java
